name: Run Private Script
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: aynibakbabm/private-repo
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: .priv
          persist-credentials: false

      - name: Run private script
        run: |
          chmod +x .priv/script.sh
          bash .priv/script.sh
