name: Run Private park.sh (quiet, masked, 50 runners)

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Target URL (https://...)"
        required: true
      countries:
        description: "EU,AM,... (15 adet; boşsa default)"
        required: false
        default: "EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 370
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        runner_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                       10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
                       20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                       30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
                       40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

    steps:
      - name: Mask inputs in logs
        run: |
          echo "::add-mask::${{ inputs.url }}"
          echo "::add-mask::${{ inputs.countries }}"
          echo "::add-mask::TARGET_URL=${{ inputs.url }}"
          echo "::add-mask::COUNTRIES=${{ inputs.countries }}"
