name: Trigger Park

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
      countries:
        required: false
        default: "EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU"

jobs:
  call-private:
    uses: aynibakbabm/private-repo/.github/workflows/park.yml@main
    with:
      url: ${{ inputs.url }}
      countries: ${{ inputs.countries }}
    secrets: inherit
