name: Run Private park.sh (debug mode)

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Target URL (https://...)"
        required: true
      countries:
        description: "EU,AM,... (15 adet; boşsa default)"
        required: false
        default: "EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU,AM,EU"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 370
    permissions:
      contents: read

    steps:
      - name: Mask inputs in logs
        run: |
          echo "::add-mask::${{ inputs.url }}"
          echo "::add-mask::${{ inputs.countries }}"

      - name: Checkout private repo (read-only)
        uses: actions/checkout@v4
        with:
          repository: aynibakbabm/private-repo   # <- repo adını doğrula
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: .priv
          persist-credentials: false

      - name: Preflight (deps & docker sanity)
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y curl
          docker --version

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run park.sh (debug output)
        env:
          TARGET_URL: ${{ inputs.url }}        # scriptte TARGET_URL bekleniyor
          COUNTRIES: ${{ inputs.countries }}
        shell: bash
        run: |
          set -e
          chmod +x .priv/park.sh || true
          # Debug mod: tüm çıktı doğrudan loglarda
          .priv/park.sh

      - name: Secure cleanup
        if: always()
        run: |
          rm -f run.log || true
